create table UserInfo (

user_id number Not Null , 
u_email VARCHAR2(20) Not Null ,
u_password VARCHAR2(20) Not Null , 
u_f_name VARCHAR2(20) Not Null ,
u_m_name VARCHAR2(20) Not Null , 
u_l_name VARCHAR2(20) Not Null , 
state VARCHAR2(20) Not Null , 
district VARCHAR2(20) Not Null ,
city VARCHAR2(20) Not Null , 
PinCode NUMBER Not Null , 
line1 VARCHAR2(200) Not Null , 
u_role CHAR(2) CHECK(u_role IN ( 'A','P','HS' )) Not Null,

PRIMARY KEY (user_id)

);

create SEQUENCE userinfo_seq;

Create or REPLACE TRIGGER userinfo_trigger
BEFORE INSERT ON UserInfo
FOR EACH ROW 
BEGIN
    SELECT userinfo_seq.Nextval into :new.user_id FROM dual;
END;

SELECT * FROM userinfo ;

INSERT INTO userinfo ( u_password , u_f_name ,u_m_name , u_l_name , state , district , 
city , PinCode , line1 , u_role  ) VALUES ( '123' , 'JP' , 'B' , 'P' , 'Maha' , 'Thane' ,
'Diva' , 400612 , '307 / Shri Sai Swami Apt. NR Nagar' , 'A' );

create table UserDetails (

user_id number GENERATED BY DEFAULT AS IDENTITY , 
u_email VARCHAR2(20) Not Null UNIQUE ,
u_password VARCHAR2(20) Not Null , 
u_phone NUMBER Not Null UNIQUE ,
u_f_name VARCHAR2(20) Not Null ,
u_m_name VARCHAR2(20) Not Null , 
u_l_name VARCHAR2(20) Not Null , 
state VARCHAR2(20) Not Null , 
district VARCHAR2(20) Not Null ,
city VARCHAR2(20) Not Null , 
PinCode NUMBER Not Null , 
line1 VARCHAR2(200) Not Null , 
u_role CHAR(2) CHECK(u_role IN ( 'A','P','HS' )) Not Null,

PRIMARY KEY (user_id)
);

INSERT INTO userdetails ( u_email , u_password , u_phone , u_f_name ,u_m_name , u_l_name , state , district , 
city , PinCode , line1 , u_role  ) VALUES ( 'jp@gmail.com' , '123' , 9967824801 , 'JP' , 'B' , 'P' , 'Maha' , 'Thane' ,
'Diva' , 400612 , '307 / Shri Sai Swami Apt. NR Nagar' , 'A' );

INSERT INTO userdetails ( u_email , u_password , u_phone , u_f_name ,u_m_name , u_l_name , state , district , 
city , PinCode , line1 , u_role  ) VALUES ( 'vp@gmail.com' , '123' , 9967824811 , 'VP' , 'B' , 'P' , 'Maha' , 'Thane' ,
'Diva' , 400612 , '307 / Shri Sai Swami Apt. NR Nagar' , 'HS' );

SELECT * FROM userdetails ;


create table Hotel (
H_id number GENERATED BY DEFAULT AS IDENTITY, 
H_name varchar2(20), 
state varchar2(20), 
district varchar2(20), 
city varchar2(20), 
PinCode number, 
H_No_room number,
H_No_VacantRoom number, 
Admin_id number, 
L_id number,
PRIMARY KEY (H_id),
FOREIGN KEY(Admin_id) REFERENCES AdminDetails(Admin_id) 
    ON DELETE CASCADE ,
FOREIGN KEY(L_id) REFERENCES Location(L_id) 
    ON DELETE CASCADE 
);

create table Room ( 
R_id number GENERATED BY DEFAULT AS IDENTITY , 
R_Type varchar2(20), 
R_cost number , 
r_beds number, 
r_days number, 
r_night number, 
Staff_id number, 
H_id number ,
PRIMARY KEY (R_id),
FOREIGN KEY(Staff_id) REFERENCES HotelStaffDetails(Staff_id) 
    ON DELETE CASCADE ,
FOREIGN KEY(H_id) REFERENCES Hotel(H_id) 
    ON DELETE CASCADE 
);

insert into train (TRAIN_NO , TRAIN_NAME , COST_PER_SEAT , SOURCE_STATE , SOURCE_DISTRICT , SOURCE_CITY , SOURCE_PINCODE , SOURCE_LINE , DESTN_STATE , DESTN_DISTRICT , DESTN_CITY , DESTN_PINCODE , DESTN_LINE , DEPARTURE_DATE , DEPARTURE_TIME , ARRIVAL_DATE , ARRIVAL_TIME , ADMIN_ID ) values('20112' , 'BSS Express' , 400 , 'Maha' , 'Mum' , 'Mum' , 400612 , '307/Apt.' , 'Odisha' , 'Ganjam' , 'Brahmapur' , 760011 , 'R Street' , '12-Mar-2021' , '10:00' , '14-Mar-2021' , '22:00' , 1 ) ;